### ISSUE TITLE
readrc name collision

### ISSUE THREAD

**Issue by s3ththompson** [kaelzhang/readrc#1]
Hi Kael,

I noticed you claimed my npm repo `readrc`. Is there any chance you'd *please* consider renaming your project or going with a different npm name?

Although I hadn't published a new version to npm, [readrc](https://github.com/s3ththompson/readrc) is an in-progress project with a website https://readrc.club and a [conference talk](https://peer-to-peer-web.com/nyc) (see Seth Thompson). You can read more about my ambitions for the project [here](https://www.dropbox.com/s/fgjrobdgwmd8t8l/Readrc.pdf?dl=0).

Happy to chat more over any medium (Twitter, email, here, etc.).

Thanks for your understanding,
Seth

**Comment by kaelzhang** [comment]
Hi，Seth

I see. Thanks for your quick reply. I’ll pick another name :)

Seth Thompson <notifications@github.com>于2018年8月3日 周五上午3:00写道：

**Comment by s3ththompson** [comment]
🙏🙏🙏 thank you! I really appreciate your understanding. Can you add me back as a collaborator on the npm module?

Will keep my eye on this project--looks very useful!

**Comment by kaelzhang** [comment]
Invited 😄 

/close

**Comment by s3ththompson** [comment]
@kaelzhang Oh, thank you! I actually meant the npm module: https://www.npmjs.com/package/readrc as it seems npm already removed my access to publish

**Comment by kaelzhang** [comment]
@s3ththompson Oh, oops, sorry for that. I have owner-added you to `readrc`. 

The repo has been renamed to `rc-parser` and published to npm as [https://www.npmjs.com/package/rc-parser](https://www.npmjs.com/package/rc-parser).

The npm package `readrc` is yours.
